### ISSUE TITLE
KVK時の取得について

### ISSUE THREAD

**Issue by sushi181** [iwbc/rok-scan-stats#1]
KVK期間中は個人戦力ランキングが全ての王国のランキングになりますが王国単位での取得はどのようにすれば良いでしょうか

**Comment by iwbc** [comment]
@sushi181 ロストキングダムにいるアカウントでランキングを表示すると全王国のものが表示されてしまうので、計測対象の王国にいるアカウントで実行してください。計測専用のアカウントをつくることをおすすめします（政庁レベル8だとCAPTCHAもめったに出ません）
